name: ETL Pipeline demo

on:
    push:
        branches:
        - main

jobs:
    extract-data-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: run extract.py
              run: python .github/workflows/extract.py

    transform-data-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: run transform.py
              run: python .github/workflows/transform.py

    load-data-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: run load.py
              run: python .github/workflows/load.py
