name: ETL Pipeline demo

on:
    push:
        branches:
        - main

jobs:
    extract-data-job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: setup python
              uses: actions/setup-python@v6
              with:
                 python-version: '3.10' 

            - name: show python version
              run: python --version
             
            - name: install required dependencies
              run: pip install pandas
              
            - name: run extract.py
              run: python .github/workflows/extract.py

    transform-data-job:
        runs-on: ubuntu-latest
        needs: extract-data-job
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: show python version
              run: python --version

            - name: run transform.py
              run: python .github/workflows/transform.py

    load-data-job:
        runs-on: ubuntu-latest
        needs: transform-data-job
        steps:
            - name: checkout code
              uses: actions/checkout@v2

            - name: show python version
              run: python --version

            - name: run load.py
              run: python .github/workflows/load.py
